apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${{ values.namespace }}

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/name: ${{ values.name }}
  app.kubernetes.io/managed-by: backstage

images:
  - name: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.name }}
    newTag: latest
